"""add_external_sub

Revision ID: 1ee51688053d
Revises: f54fd6e73db6
Create Date: 2026-02-08 23:10:31.155043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ee51688053d'
down_revision: Union[str, Sequence[str], None] = 'f54fd6e73db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_habits_user_id'), table_name='habits')
    op.drop_table('habits')
    op.drop_table('habit_logs')
    op.drop_index(op.f('rag_chunks_embedding_idx'), table_name='rag_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_column('rag_chunks', 'embedding')
    op.drop_index(op.f('user_memories_embedding_idx'), table_name='user_memories', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_column('user_memories', 'embedding')
    op.add_column('users', sa.Column('external_sub', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_external_sub'), 'users', ['external_sub'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_external_sub'), table_name='users')
    op.drop_column('users', 'external_sub')
    op.add_column('user_memories', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.create_index(op.f('user_memories_embedding_idx'), 'user_memories', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.add_column('rag_chunks', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.create_index(op.f('rag_chunks_embedding_idx'), 'rag_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_table('habit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('habit_logs_pkey'))
    )
    op.create_table('habits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_habits_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('habits_pkey'))
    )
    op.create_index(op.f('ix_habits_user_id'), 'habits', ['user_id'], unique=False)
    # ### end Alembic commands ###
