"""add checkin schedules

Revision ID: a1b6ec20ca55
Revises: dcf7a3654384
Create Date: 2026-02-06 23:45:13.724497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b6ec20ca55'
down_revision: Union[str, Sequence[str], None] = 'dcf7a3654384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkin_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tz', sa.String(length=64), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkin_schedules_id'), 'checkin_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_checkin_schedules_user_id'), 'checkin_schedules', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkin_schedules_user_id'), table_name='checkin_schedules')
    op.drop_index(op.f('ix_checkin_schedules_id'), table_name='checkin_schedules')
    op.drop_table('checkin_schedules')
    # ### end Alembic commands ###
