"""Add embedding column to user_memories

Revision ID: b34f43cee023
Revises: 1ee51688053d
Create Date: 2026-02-08 23:28:04.356897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'b34f43cee023'
down_revision: Union[str, Sequence[str], None] = '1ee51688053d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_memories', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_memories', 'embedding')
    # ### end Alembic commands ###
